on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
name: Docker dev images
jobs:
  backend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: bobnetnetwork/cms
          tags: backend-dev
          path: ./
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: bobesz
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: bobnetnetwork/cms-backend/backend-dev
          tags: latest
          path: ./
